# Generated by Django 2.1.3 on 2019-03-13 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shoes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=11, verbose_name='颜色')),
                ('size', models.IntegerField(verbose_name='大小')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='用户姓名')),
                ('phone', models.CharField(max_length=256, verbose_name='用户电话')),
                ('user_shoes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Shoes')),
            ],
        ),
    ]
